### PR TITLE
[FIX] Add ``-cw256`` flag for images with FoV > 256 voxels

### LINKED ISSUE #29: ERROR! FOV=289.000 > 256 Include the flag -cw256 with recon-all!
Originally reported at https://neurostars.org/t/freesurfer-error-fov-256

For files with unusually large FOV freesurfer needs to perform cropping. Example image
image

Suggested solution: detect if FOV is larger than 256 in any direction and add `-cw256` flag to recon-all. Add a red warning to the reports to check the outputs carefully.

### PR DESCRIPTION
**Pull request by oesteban**
Close #29

### CODE REVIEW

**Comment by sandhitsu** [comment]
I saw the last message at https://github.com/poldracklab/smriprep/issues/52 which says the fix for this is now available in fmriprep. However, I just tried with 1.3.0.post3 I am still getting the error

ERROR! FOV=282.000 > 256
Include the flag -cw256 with recon-all!
Inspect orig.mgz to ensure the head is fully visible.

**Comment by sandhitsu** [comment]
Just verified that 1.3.0.post3 still produces this error.

**Comment by sandhitsu** [comment]
bump!

**Comment by effigies** [comment]
Hi @sandhitsu. Sorry for the delay; generally posting on a closed issue is going to be harder for us to notice. If this issue persists for you, please open.a new issue.

I suspect that the issue is that you have sub-millimeter resolution, and FreeSurfer's `-cw256` conformation is mutually exclusive with `-hires`. You can use `--no-submm-recon` to ensure that conformation takes place or manually crop to <(256mm)^3 to continue using sub-millimeter reconstruction.

For more information, see [Neurostars #2171](https://neurostars.org/t/freesurfer-error-fov-256/2171).

**Comment by sandhitsu** [comment]
Thanks. I'll look in that thread. I don't think the data is sub-mm but will double check.

**Pull request merged**
